"""add profile fields

Revision ID: 5b7581f67ae6
Revises: f23ca640eaa9
Create Date: 2026-06-16 10:29:20.225498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7581f67ae6'
down_revision: Union[str, Sequence[str], None] = 'f23ca640eaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flat_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('floor_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('resident_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('family_members', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('vehicle_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vehicle_details')
    op.drop_column('users', 'family_members')
    op.drop_column('users', 'resident_type')
    op.drop_column('users', 'floor_number')
    op.drop_column('users', 'flat_number')
    # ### end Alembic commands ###
